[phases.setup]
packages = ["python3", "python3Packages.pip"]

[phases.install]
commands = ["pip install -r requirements.txt"]

[phases.build]
commands = []

[phases.deploy]
commands = ["gunicorn User_project.wsgi"]