# Generated by Django 5.2.2 on 2025-07-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0004_notification_content_type_notification_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_ban_user', 'Can ban other users')]},
        ),
    ]
