# Generated by Django 5.2.2 on 2025-07-01 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_delete_any_message', 'Can delete any message')]},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created'], 'permissions': [('can_delete_any_room', 'Can delete any room')]},
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
