# Generated by Django 5.2.2 on 2025-07-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
