# Generated by Django 5.2.2 on 2025-07-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_share_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
